spring:
  config:
    import: "aws-parameterstore:/ticketing/prod/"

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

management:
  server:
    port: 9091

  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

server:
  tomcat:
    mbeanregistry:
      enabled: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1

    instances:
      payment:
        ignore-exceptions:
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
          - io.github.resilience4j.bulkhead.BulkheadFullException
          - com.ticketing.payment.PaymentNonRetryableException

  retry:
    retry-aspect-order: 2

    instances:
      payment:
        retry-exceptions:
          - com.ticketing.payment.PaymentRetryableException
        ignore-exceptions:
          - com.ticketing.payment.PaymentNonRetryableException
          - io.github.resilience4j.bulkhead.BulkheadFullException

  ratelimiter:
    instances:
      payment:
        limit-for-period: 20
        limit-refresh-period: 1s
        timeout-duration: 0
