spring:
  application:
    name: concert-ticketing-api

management:
  metrics:
    tags:
      application: ticketing-api

    distribution:
      percentiles-histogram:
        http.server.requests: true