spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

management:
  server:
    port: 9091

  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

server:
  tomcat:
    mbeanregistry:
      enabled: true
